version: 2
jobs:
  test:
    docker:
      - image: closeio/circle_ubuntu:20170824145424
    working_directory: /home/circle/devops
    steps:
      - checkout

      - run:
          name: Setup - Create virtualenv directory
          command: mkdir ~/virtualenvs

      - run:
          name: Setup - Create test virtualenv
          command: if [ ! -d ~/virtualenvs/tests ]; then  virtualenv ~/virtualenvs/tests; fi

      - run:
          name: Setup - Install test requirements
          command: source ~/virtualenvs/tests/bin/activate && pip install -U pip && pip install --exists-action=s --no-deps -r /home/circle/devops/requirements_tests.txt

      - run:
          name: Test - Flake8
          command: cd ~/devops && source ~/virtualenvs/tests/bin/activate && flake8
  minikube-testing:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      # Using minikube steps from https://github.com/gavinzhou/ci-minikube
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo minikube start --vm-driver=none
      - run:
          command: |
            sudo minikube update-context
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          command: |
            sudo kubectl cluster-info

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - minikube-testing
