version: 2
jobs:
  test:
    docker:
      - image: closeio/circle_ubuntu:20170824145424
    working_directory: /home/circle/devops
    steps:
      - checkout

      - run:
          name: Setup - Create virtualenv directory
          command: mkdir ~/virtualenvs

      - run:
          name: Setup - Create test virtualenv
          command: if [ ! -d ~/virtualenvs/tests ]; then  virtualenv ~/virtualenvs/tests; fi

      - run:
          name: Setup - Install test requirements
          command: source ~/virtualenvs/tests/bin/activate && pip install -U pip && pip install --exists-action=s --no-deps -r /home/circle/devops/requirements_tests.txt

      - run:
          name: Test - Flake8
          command: cd ~/devops && source ~/virtualenvs/tests/bin/activate && flake8
  minikube-testing:
    machine:
      image: circleci/classic:201808-01
    environment:
      K8S_VERSION: v1.10.11
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.30.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      # Using minikube steps from https://github.com/gavinzhou/ci-minikube
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo minikube config set WantReportErrorPrompt false
      - run:
          command: |
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048 --kubernetes-version=${K8S_VERSION}
      - run:
          command: |
            sudo minikube update-context
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          name: fix RBAC
          command: |
            # make default account cluster-admin
            kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
      - run:
          name: dump cluster-info
          command: |
            kubectl cluster-info
            kubectl get po --all-namespaces
      - run:
          name: update apt
          command: |
            sudo apt-get update
            sudo systemctl stop apt-daily.service
            sudo systemctl kill --kill-who=all apt-daily.service
            while ! (sudo systemctl list-units --all apt-daily.service | fgrep -q dead); do sleep 1; done
      - run:
          name: install python dependencies
          command: |
            sudo apt-get install python-all-dev
            sudo pip install --no-deps -r /home/circleci/project/scripts/k8s-cicd/requirements.txt
            sudo pip install ipaddress
      - run:
          command: |
            sudo /home/circleci/project/scripts/k8s-cicd/k8scicd.sh -p test -d /home/circleci/project/scripts/k8s-cicd/tests/ -s

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - minikube-testing
